import { FeatureConfig, ActivityLog, RateLimitConfig, UsageStatPoint, BotInstance } from './types';

export const INITIAL_BOT_INSTANCE: BotInstance = {
  id: 'inst-7881-bd92',
  nomor_wa: '+62 812-***-9081',
  status: 'connected',
  session_name: 'verand_primary_worker',
  connected_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  battery_level: 92,
  push_name: 'Verand Assistant',
  uptime_seconds: 14420,
};

export const INITIAL_FEATURES: FeatureConfig[] = [
  {
    id: 'feat-sticker-maker',
    feature_key: 'sticker_maker',
    name: 'Stiker Maker',
    tagline: 'Konversi otomatis foto/video pendek ke stiker WhatsApp WebP 512x512 + custom EXIF pack',
    category: 'core',
    is_enabled: true,
    command_trigger: '!sticker',
    aliases: ['!s', '!stiker', '!swm'],
    extra_settings: {
      pack_name: 'Verand Pack',
      author_name: 'Made with Verand.Bot',
      max_duration_sec: 10,
      quality: 'high',
    },
  },
  {
    id: 'feat-sticker-to-media',
    feature_key: 'sticker_to_media',
    name: 'Stiker to Media',
    tagline: 'Ubah kembali stiker WebP menjadi foto PNG/JPG atau animasi GIF/MP4',
    category: 'core',
    is_enabled: true,
    command_trigger: '!tomedia',
    aliases: ['!toimg', '!togif', '!tovid'],
    extra_settings: {
      quality: 'high',
    },
  },
  {
    id: 'feat-downloader',
    feature_key: 'downloader',
    name: 'Media Downloader',
    tagline: 'Unduh video atau audio dari tautan TikTok (no-watermark), Instagram Reels, dan YouTube',
    category: 'media',
    is_enabled: true,
    command_trigger: '!dl',
    aliases: ['!tt', '!ig', '!yt'],
    extra_settings: {
      supported_platforms: ['TikTok', 'Instagram', 'YouTube'],
    },
  },
  {
    id: 'feat-auto-reply',
    feature_key: 'auto_reply',
    name: 'Auto-Reply & FAQ',
    tagline: 'Balas pesan otomatis berdasarkan kata kunci tertentu untuk admin grup atau toko',
    category: 'utility',
    is_enabled: true,
    command_trigger: '!faq',
    aliases: ['!auto', '!info'],
    extra_settings: {
      auto_replies: [
        { trigger: 'halo', response: 'Halo! Verand Bot aktif 24/7. Ketik !menu untuk melihat fitur.' },
        { trigger: 'harga', response: 'Layanan Verand Bot tersedia paket personal gratis & tier komunitas.' },
        { trigger: 'rules', response: 'Harap patuhi aturan grup: dilarang spam, dilarang kirim konten terlarang.' },
      ],
    },
  },
  {
    id: 'feat-group-tools',
    feature_key: 'group_tools',
    name: 'Grup Management Tools',
    tagline: 'Sambutan member baru, deteksi anti-link spam, dan utilitas moderasi admin',
    category: 'utility',
    is_enabled: false,
    command_trigger: '!group',
    aliases: ['!welcome', '!antilink'],
    extra_settings: {
      anti_link: true,
      welcome_message: 'Selamat datang di grup! Silakan perkenalkan diri dan patuhi aturan.',
    },
  },
  {
    id: 'feat-ai-chat',
    feature_key: 'ai_chat',
    name: 'AI Chat Assistant',
    tagline: 'Tanya jawab cerdas langsung di WhatsApp menggunakan model AI Gemini / LLM',
    category: 'ai_fun',
    is_enabled: true,
    command_trigger: '!ai',
    aliases: ['!tanya', '!ask', '!gemini'],
    is_beta: true,
    extra_settings: {
      ai_system_prompt: 'Kamu adalah asisten bot WhatsApp ramah, ringkas, dan berbahasa Indonesia gaul santun.',
    },
  },
  {
    id: 'feat-tts-converter',
    feature_key: 'tts_converter',
    name: 'Text-to-Speech & Converter',
    tagline: 'Konversi teks menjadi rekaman suara WhatsApp (VN) dan konversi mata uang/satuan',
    category: 'utility',
    is_enabled: false,
    command_trigger: '!tts',
    aliases: ['!suara', '!kurs'],
    extra_settings: {
      quality: 'high',
    },
  },
  {
    id: 'feat-text-games',
    feature_key: 'text_games',
    name: 'Game Teks Komunitas',
    tagline: 'Tebak kata, kuis cepat, dan asah otak untuk meramaikan grup teman',
    category: 'ai_fun',
    is_enabled: false,
    command_trigger: '!game',
    aliases: ['!tebak', '!kuis'],
    is_beta: true,
    extra_settings: {},
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'log-101',
    feature_key: 'sticker_maker',
    feature_name: 'Stiker Maker',
    command: '!s (reply image 512x512)',
    sender_masked: '62812***456',
    status: 'success',
    execution_time_ms: 240,
    created_at: new Date(Date.now() - 45000).toISOString(),
    detail: 'WebP 512x512 with EXIF [Verand Pack / Verand.Bot] sent.',
  },
  {
    id: 'log-102',
    feature_key: 'ai_chat',
    feature_name: 'AI Chat Assistant',
    command: '!ai apa perbedaan Next.js dan Vite?',
    sender_masked: '62857***890',
    status: 'success',
    execution_time_ms: 810,
    created_at: new Date(Date.now() - 110000).toISOString(),
    detail: 'Gemini flash token response: 184 words returned.',
  },
  {
    id: 'log-103',
    feature_key: 'downloader',
    feature_name: 'Media Downloader',
    command: '!dl https://vt.tiktok.com/ZS.../',
    sender_masked: '62813***112',
    status: 'success',
    execution_time_ms: 1250,
    created_at: new Date(Date.now() - 250000).toISOString(),
    detail: 'TikTok no-watermark MP4 video sent (3.4 MB).',
  },
  {
    id: 'log-104',
    feature_key: 'sticker_maker',
    feature_name: 'Stiker Maker',
    command: '!sticker (spam burst 2x < 3s)',
    sender_masked: '62812***456',
    status: 'rate_limited',
    execution_time_ms: 12,
    created_at: new Date(Date.now() - 290000).toISOString(),
    detail: 'Ditolak: Jeda pesan minimal 3.0 detik (§8 Anti-Abuse).',
  },
  {
    id: 'log-105',
    feature_key: 'sticker_to_media',
    feature_name: 'Stiker to Media',
    command: '!toimg (reply sticker)',
    sender_masked: '62878***932',
    status: 'success',
    execution_time_ms: 180,
    created_at: new Date(Date.now() - 410000).toISOString(),
    detail: 'WebP extracted to transparent PNG (480 KB).',
  },
  {
    id: 'log-106',
    feature_key: 'auto_reply',
    feature_name: 'Auto-Reply & FAQ',
    command: 'halo kak info dong',
    sender_masked: '62821***304',
    status: 'success',
    execution_time_ms: 45,
    created_at: new Date(Date.now() - 580000).toISOString(),
    detail: 'Keyword match: "halo" -> auto response sent.',
  },
];

export const INITIAL_RATE_LIMIT: RateLimitConfig = {
  cooldown_seconds: 3,
  command_prefix: '!',
  max_per_minute: 20,
  anti_spam_active: true,
  blacklisted_senders: ['62899***000'],
  whitelist_groups_only: false,
  whitelisted_groups: ['Komunitas Dev ID', 'Grup Uji Coba Bot'],
};

export const INITIAL_USAGE_STATS: UsageStatPoint[] = [
  { date: 'Senin', commands_count: 142, stickers_created: 88, media_downloaded: 34, ai_chats: 20 },
  { date: 'Selasa', commands_count: 198, stickers_created: 112, media_downloaded: 52, ai_chats: 34 },
  { date: 'Rabu', commands_count: 245, stickers_created: 145, media_downloaded: 60, ai_chats: 40 },
  { date: 'Kamis', commands_count: 210, stickers_created: 120, media_downloaded: 55, ai_chats: 35 },
  { date: 'Jumat', commands_count: 320, stickers_created: 190, media_downloaded: 80, ai_chats: 50 },
  { date: 'Sabtu', commands_count: 480, stickers_created: 290, media_downloaded: 110, ai_chats: 80 },
  { date: 'Minggu', commands_count: 530, stickers_created: 330, media_downloaded: 125, ai_chats: 75 },
];
